
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ristorante_da_azzurro
    username: root
    password: qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

    
logging:
  level:
    org.springframework.security: DEBUG